celestiaorg/celestia-zkevm-ibc-demo

Makefile
Improve the makefile so that each command has relevant help output. Removes unused variables.
```
$ make
Choose a command run in celestia-zkevm-ibc-demo:
help                   Get more info on make commands.
build                  Build the celestia-appd binary into the ./build directory.
install                Build and install the celestia-appd binary into the $GOPATH/bin directory.
mod                    Update all go.mod files.
mod-verify             Verify dependencies have expected content.
proto-gen              Generate protobuf files. Requires docker.
proto-lint             Lint protobuf files. Requires docker.
proto-check-breaking   Check if there are any breaking change to protobuf definitions.
proto-format           Format protobuf files. Requires Docker.
build-docker …
```
=> chore: improve Makefile

ibc/mpt/database.go
Fixes 
```
$ make build
--> Updating go.mod
ibc/mpt/database.go:77:59: undefined: database.Reader
ibc/mpt/test_helpers.go:25:27: cannot use newTestDatabase(rawdb.NewMemoryDatabase(), rawdb.HashScheme) (value of type *testDb) as database.NodeDatabase value in argument to gethtrie.NewEmpty: *testDb does not implement database.NodeDatabase (missing method NodeReader)
make: *** [build] Error 1
```
=> fix: `make build`

ibc/lightclients/groth16/client_state.go
Extracted from https://github.com/celestiaorg/celestia-zkevm-ibc-demo/pull/50 because @tuxcanfly will query consensus state on the Groth16 light client soon.
=> fix: setConsensusState when light client is initialized

.dockerignore
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/60
Now it takes less time to create the Docker image and 9GB isn't copied over.
```
$ make build-simapp-docker
--> Updating go.mod
--> Building Docker image
/opt/homebrew/bin/docker build -t ghcr.io/celestiaorg/simapp -f docker/Dockerfile .
[+] Building 88.6s (15/15) FINISHED
=> [internal] load build definition from Dockerfile                                                                                                                                                         3.7s
=> => transferring dockerfile: 1.39kB                                                                                                                                                                       0.0s
=> [internal] load metadata for …
```
=> chore: decrease make build-simapp-docker time

Makefile
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/37
=> chore: make check-dependencies

docker-compose.yml
Prior to this PR the celestia-prover wasn't in the same Docker network as the other services so it couldn't connect to the Reth node or SimApp. Also it was trying to use the Celestia validator instead of SimApp validator.
=> fix: celestia prover connections

Cargo.lock, provers/celestia-prover/Cargo.toml
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/87
```
make start
make setup
make transfer
make relay
```
Generated a proof that was able to update the Tendermint light client on EVM
=> chore(deps): upgrade to SP1 v4

ibc/lightclients/groth16/witness.go, provers/blevm/common/src/lib.rs
Comments captured during a sync.
=> docs: comments for BlevmAggOutput and PublicWitness

provers/blevm/blevm-prover/src/lib.rs
As the error message suggests, switching to groth16 proofs fixed the issue:
> Error: status: InvalidArgument, message: "core proofs above 5000000 cycles are not supported - please request a compressed, groth16, or plonk proof instead", details: [], metadata: MetadataMap { headers: {"server": "awselb/2.0", "date": "Wed, 29 Jan 2025 06:32:45 GMT", "content-type": "application/grpc", "content-length": "0", "access-control-allow-origin": "*", "vary": "origin, access-control-request-method, access-control-request-headers"} }
Fixes #113
=> fix(blevm): groth16 instead of core proofs

provers/blevm/README.md, provers/blevm/script/src/bin/main.rs
Now that we can generate blevm proofs, I wanted to measure the proof generation time to double check that we actually need the mock proofs. It takes 6 minutes so seems worth pursuing the mock proofs for now.
```
Generating proof...
stderr: WARNING: Using insecure random number generator.
stdout: Blob commitment: 7946cf528edd745efb25201246e647d5aaca3fb52bf0f606b695b4ab0bd33f4c
Generated proof in 348.35040425s.
Saving proof to proof.bin
Saved proof.
```
=> docs: measure proof generation time

provers/blevm/Cargo.lock, provers/blevm/Cargo.toml, provers/blevm/README.md, provers/blevm/blevm-aggregator/src/buffer.rs, provers/blevm/blevm-mock/Cargo.toml, provers/blevm/blevm-mock/src/main.rs, provers/blevm/blevm-prover/src/lib.rs, provers/blevm/blevm/src/main.rs, provers/blevm/common/src/lib.rs, provers/blevm/script/Cargo.toml, provers/blevm/script/build.rs, provers/blevm/script/src/bin/main.rs
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/93
- Deleted provers/blevm/elf/riscv32im-succinct-zkvm-elf because https://succinctlabs.notion.site/sp1-v4-migration-guide states we shouldn't commit the ELFs to source control.
- Modifies the script so that it can run in either: prove or execute mode.
- Modifies the script so that it can run on `blevm` or `blevm-mock` ELF
- Added proof generation time to README
=> feat: implement blevm-mock

.dockerignore
I was trying to build a celestia-prover Docker image and it took forever transferring over 20 GB of context. It appears to have been copying nested `target/` directories inside the blevm subdirectory. This change makes Docker ignore all the target directories, not just the one at the repo root.
=> chore(docker): ignore all target directories

Cargo.toml
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/136
The `subdir` key wasn't necessary:
> Cargo fetches the git repository at that location and traverses the file tree to find Cargo.toml file for the requested crate anywhere inside the git repository.
Ref: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html
No more warnings 
```
$ cargo build
Compiling sp1-ics07-tendermint-prover v0.1.0 (https://github.com/cosmos/solidity-ibc-eureka.git?branch=main#ec5227e7)
Compiling mock-membership v0.1.0 (/Users/rootulp/git/rootulp/celestiaorg/celestia-zkevm-ibc-demo/programs/sp1/mock-membership)
Compiling mock-update-client v0.1.0 (/Users/rootulp/git/rootulp/celestiaorg/celestia-zkevm-ibc-demo/programs/sp1/mock-update-client)
Compiling celestia-prover v0.1.0 …
```
=> fix: warning for unused manifest key

provers/blevm/README.md, provers/blevm/blevm-aggregator/src/main.rs, provers/blevm/blevm-prover/src/lib.rs, provers/blevm/blevm-prover/src/proofs.rs, provers/blevm/script/build.rs, provers/blevm/script/src/bin/main.rs
Fixes #148 Implements multiple proof aggregation by iterating over the range. Extends `blevm-aggregator` for variable number of proofs. Also adds helpers to `blevm-prover` so that the library can be used to generate range proofs.
=> fix(blevm): support multiple proof aggregation

README.md, provers/blevm/README.md
Hi! The links were pointing to outdated or incorrect URLs related to Succinct's SP1 documentation.
=> docs: fix Succinct links

provers/celestia-prover/prover/src/main.rs, provers/celestia-prover/prover/src/prover.rs
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/86
```
$ cargo run -p celestia-prover
SP1_Prover mode: network
```
It already logs when it finishes generating proofs. Ex:
```
Generated membership proof for height: 12039
```
=> chore: emit more logs from celestia-prover

provers/blevm/blevm/src/main.rs
The sp1 program output is [serialized by default](https://docs.succinct.xyz/docs/sp1/writing-programs/inputs-and-outputs#committing-data
), serializing it before commiting it causes issues while reading the output, e.g. interchanged height and gas used. There were other discrepancies as well, such as header not matching the expected evm header.
Before:
```
cd provers/blevm/script
cargo run -- --execute
```
> BlevmOutput { blob_commitment: [196, 0, 0, 0, 0, 0, 0, 0, 121, 70, 207, 82, 142, 221, 116, 94, 251, 37, 32, 18, 70, 230, 71, 213, 170, 202, 63, 181, 43, 240, 246, 6], header_hash: [182, 149, 180, 171, 11, 211, 63, 76, 133, 106, 134, 184, 20, 76, 104, 254, 40, 136, 41, 140, 238, 199, 193, 86, 163, 56, 170, 193, 61, 146, 213, 227], prev_header_hash: [194, 70, 12, 164, 151, 147, 237, …
=> fix(blevm): fix blevm output

Makefile, README.md
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/207
```
$ make lint
--> Running golangci-lint
--> Running markdownlint
--> Running hadolint
```
=> docs: fix markdown links

provers/blevm/blevm-mock/src/main.rs
Same as #201 but for the mock program. Fixed output:
> cd provers/blevm/blevm-mock
> cargo run -- --execute --mock --input-path=input/blevm/1/18884864.bin --inclusion-block=2988873
> 
> BlevmOutput { blob_commitment: [196, 0, 0, 0, 0, 0, 0, 0, 121, 70, 207, 82, 142, 221, 116, 94, 251, 37, 32, 18, 70, 230, 71, 213, 170, 202, 63, 181, 43, 240, 246, 6], header_hash: [182, 149, 180, 171, 11, 211, 63, 76, 133, 106, 134, 184, 20, 76, 104, 254, 40, 136, 41, 140, 238, 199, 193, 86, 163, 56, 170, 193, 61, 146, 213, 227], prev_header_hash: [194, 70, 12, 164, 151, 147, 237, 105, 187, 154, 187, 153, 78, 140, 25, 59, 84, 254, 152, 25, 224, 239, 83, 45, 145, 73, 226, 110, 100, 51, 95, 167], **height: 18884864, gas_used: 14900876081506838043**, beneficiary: [4, 26, 65, 0, 0, 0, 0, 0, 149, 34, 34, 144, …
=> fix(blevm-mock): fix blevm mock output

provers/blevm/README.md, testing/demo/pkg/setup/consts.go, testing/demo/pkg/setup/groth16.go, testing/demo/pkg/transfer/consts.go, testing/demo/pkg/transfer/relay.go
Addresses 3 FLUPs from @cmwaters review on https://github.com/celestiaorg/celestia-zkevm-ibc-demo/pull/186:
1. Create Groth16 client with STF verifier key from EVM prover. The EVM prover doesn't return a membership verifier key yet.
2. Clarify a comment for relayByTx
3. Remove `FungibleTokenPacketData` because it's not needed until we resolve a TODO
```shell
make stop && make demo
Got state transition verifier key: 00d03e583079d6e27e3904d12548a44e7914721bb977e2a81faafa747092b7de
```
and then manually verified that matches the EVM prover
```
$ grpcurl -plaintext localhost:50052 celestia.prover.v1.Prover/Info
{
"stateTransitionVerifierKey": "0x00d03e583079d6e27e3904d12548a44e7914721bb977e2a81faafa747092b7de"
}
```
=> fix: create groth16 client with STF verifier key from EVM prover

Makefile
- Removed make targets that are no longer needed
- Reordered commands into groups
- Made the `install`, `publish`, and `build` commands do it for all services
=> refactor: makefile

README.md, docs/ARCHITECTURE.md, docs/CONTRIBUTING.md
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/170 by removing the old architecture doc and moving the more up to date README contents there. Then updated some of the steps and added a sequence diagram.
=> docs: de-duplicate README and architecture

Makefile, go.mod, go.sum, testing/demo/pkg/setup/tendermint.go
Update the existing demo to use `SP1_PROVER=mock` mode. Now the demo takes < 1 minute to run because it takes less than a second to generate the Celestia STF and membership proofs.
In hindsight, I should've tried this much earlier.
```
make demo 
```
still works
=> feat: deploy mock verifier contract

.vscode/settings.json, provers/blevm/Cargo.toml, provers/blevm/blevm-prover/src/lib.rs
Temporary fix before we flatten our workspace structure. ref: #116
=> fix: rust-analyzer not indexing blevm

README.md, testing/demo/pkg/setup/tendermint.go
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/240
Previously it was a hack that `make setup` relied on environment variables set by the `.env` file in solidity-ibc-eureka. This PR removes the need for that file.
```
cd solidity-ibc-eureka
mv .env .env.backup
```
```
make demo
```
still works
=> refactor: stop relying on .env file in solidity-ibc-eureka

Makefile
Part of https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/249
cc: @MSevey
=> chore(makefile): EVM prover docker image commands

indexer/main.go
Sometimes the indexer runs into a loop:
> 2025-04-18 11:25:31 2025/04/18 15:25:31 API service started
> 2025-04-18 11:25:31 2025/04/18 15:25:31 Indexer service started
> 2025-04-18 11:25:31 2025/04/18 15:25:31 All services started successfully, running...
> 2025-04-18 11:25:31 2025/04/18 15:25:31 All services have shut down. Exiting.
This might happen if the goroutine fires _after_ `wg.Wait` due to late scheduling. Instead, we move the `wg.Add` outside of the goroutines.
=> fix(indexer): add waitgroup outside gr

provers/evm-prover/src/main.rs
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/258
I verified this works by re-running `make demo`. Previously the evm-prover would panic. Now it retries:
```
Block not found for height 14, retrying (1/3)...
indexer: requesting url - http://127.0.0.1:8080/inclusion_height/14
indexer: requesting url - http://127.0.0.1:8080/inclusion_height/15
indexer: requesting url - http://127.0.0.1:8080/inclusion_height/16
Block not found for height 16, retrying (1/3)...
indexer: requesting url - http://127.0.0.1:8080/inclusion_height/16
Block not found for height 16, retrying (2/3)...
indexer: requesting url - http://127.0.0.1:8080/inclusion_height/16
generating aggregation proof, size: 14
```
=> fix: retry indexer request

provers/evm-prover/ARCHITECTURE.md, provers/evm-prover/README.md
This PR adds a document explaining the current architecture of the evm-prover.
=> docs: add architecture doc for evm-prover

README.md, docker-compose.rollkit.yml
Found that the latest reth version does not supports the `rpc.eth-proof-window` flag. Pins the Reth version to use a specific version that supports it.
Updated README.md with some additional commands needed for the setup.
Ran everything locally to test.
=> Update Reth image version and README.md
