- Makefile
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/23
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/21
> Add demo commands to makefile

- README.md
Correctly modified invalid links.
The revised link is described in the commit. Hope this fix helps.
> docs: fix invalid links README.md

- .github/workflows/docker.yml
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/48
Will test after this PR merges to main.
> ci: publish SimApp Docker image

- .github/workflows/docker.yml
- docker/simapp.Dockerfile
Attempts to close https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/70
> fix: Docker publishing

- provers/blevm/Cargo.lock
- provers/blevm/Cargo.toml
- provers/blevm/blevm-aggregator/Cargo.toml
- provers/blevm/blevm-aggregator/src/buffer.rs
- provers/blevm/blevm-mock/Cargo.toml
- provers/blevm/blevm-prover/Cargo.toml
- provers/blevm/blevm-prover/src/lib.rs
- provers/blevm/blevm/Cargo.toml
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/105
> chore(deps): upgrade blevm to SP1 v4

- .env.example
- provers/blevm/README.md
- provers/blevm/blevm-aggregator/src/main.rs
- provers/blevm/blevm-mock/src/main.rs
- provers/blevm/blevm-prover/src/lib.rs
- provers/blevm/blevm/src/main.rs
- provers/blevm/script/build.rs
- provers/blevm/script/src/bin/main.rs
While working on https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/93, I read the blevm source code and added comments along the way. Additionally:
- Added a project layout in the README because there are a lot of creates in the blevm workspace
- Added docs on how to proxy to a DA node running in Lunaroasis 
- Extracted env variables and made them throw an informative error if any not provided
> docs: blevm code comments

- README.md
- provers/celestia-prover/README.md
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/126
> docs: use new env variable

- provers/blevm/script/build.rs
Addresses this comment: https://github.com/celestiaorg/celestia-zkevm-ibc-demo/pull/124#discussion_r1940307074
> chore: disable mock blevm elf

- .github/setup/action.yml
- .github/workflows/rust.yml
- docker/celestia_prover.Dockerfile
- provers/blevm/Cargo.toml
- provers/blevm/blevm-aggregator/Cargo.toml
- provers/blevm/blevm-mock/Cargo.toml
- provers/blevm/blevm-prover/Cargo.toml
- provers/blevm/blevm/Cargo.toml
- provers/blevm/common/Cargo.toml
- provers/blevm/rust-toolchain
- provers/blevm/script/Cargo.toml
- provers/celestia-prover/programs/sp1/mock-update-client/Cargo.toml
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/177
`make build-celestia-prover-docker` works
> fix: `make build-celestia-prover-docker`

- ibc/lightclients/groth16/groth16.pb.go
- proto/ibc/lightclients/groth16/v1/groth16.proto
- testing/demo/pkg/setup/initialise_groth16_client.go
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/166
> docs: improve `CodeCommitment` docs

- docker-compose.rollkit.yml
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/184
No more warning
> chore(deps): upgrade celestia-app

- provers/celestia-prover/prover/src/main.rs
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/188
New logs
```
client_state chainId: "zkibc-demo"
trusted_block.height: block::Height(31)
target_block.height: block::Height(381)
trusted_consensus_state: ConsensusState { timestamp: 1740780329, root: 0xd95057c4b8835631b8a3ddd6aac3f673df64aea2cd7ce6cd500760adf5d9d660, nextValidatorsHash: 0xbc4b9aae47a39635413417f7104fff9f09984d9e5f7b543e93227061c956457a }
proving from height 31 to height 381
```
> fix: celestia-prover block range logs

- .github/workflows/rust.yml
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/198
> ci: upgrade to SP1 v4.1.2

- provers/blevm/README.md
Added usage section for `blevm-tools`. Fixes #203
> docs: add blevm-tools usage

- provers/celestia-prover/prover/src/main.rs
- testing/demo/pkg/transfer/consts.go
- testing/demo/pkg/transfer/main.go
- testing/demo/pkg/transfer/query_balance.go
- testing/demo/pkg/transfer/relay.go
- testing/demo/pkg/transfer/transfer.go
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/223
- Added logs to describe balances pre/post transfer
- Removed verbose logs to clean up output
```
$ make transfer
--> Transferring tokens from simapp to the EVM roll-up
Initial balance on SimApp: 274883996352
Current balance on SimApp: 274883996192
Difference (transfer amount + gas fees): 160
Current balance on Ethereum: 100
```
> feat: query balances

- ibc/lightclients/groth16/client_state.go
Might need to be tweaked based on what a serialized mock proof looks like in practice.
> feat(lightclients/groth16): skip verification for empty proofs

- provers/celestia-prover/prover/src/prover.rs
hey team! I found duplicate words and fixed them.
> docs: remove consecutive duplicate words

- docker-compose.rollkit.yml
- testing/files/entrypoint.sh
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/255
> chore: increase EVM block time to 6 seconds

- .github/workflows/rust.yml
CI currently takes ~20mins to complete. We can optimize this by using cached dependencies as well as replacing `build` with `check`.
https://corrode.dev/blog/tips-for-faster-ci-builds/
> fix(ci): optimize build

- provers/blevm/blevm-prover/src/prover.rs
- provers/evm-prover/src/main.rs
This PR sets the defer proof verification flag in mock mode. We need this to verify mock aggregate proofs which contain mock proofs themselves.
https://docs.succinct.xyz/docs/sp1/writing-programs/proof-aggregation#proof-aggregation-in-mock-mode
Fixes #270
> fix(evm-prover): defer verification in mock mode

- provers/evm-prover/src/main.rs
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/269
Context: I want to see if this works as expected with https://github.com/celestiaorg/celestia-zkevm-ibc-demo/pull/257
> feat: remove `MAX_AGGREGATION_SIZE` limit

- .env.example
- README.md
- docker-compose.rollkit.yml
- provers/evm-prover/src/main.rs
- testing/demo/pkg/transfer/consts.go
- testing/demo/pkg/transfer/update_groth16_client.go
Closes https://github.com/celestiaorg/celestia-zkevm-ibc-demo/issues/245
> feat: use evm-prover mock proofs

- testing/demo/pkg/transfer/query_balance.go
- testing/demo/pkg/transfer/update_groth16_client.go
I noticed a few logs that clutter the console output and are kinda confusing to see so I removed them.
> chore: remove debug logs

- provers/blevm/blevm-prover/src/prover.rs
- provers/blevm/script/src/bin/aggregator.rs
- provers/blevm/script/src/bin/main.rs
- provers/evm-prover/src/main.rs
Closes https://github.com/celestiaorg/celestia-zkevm-hl-testnet/issues/8
Manually tested:
```
root@yb-playground:~/yb/celestia-zkevm-ibc-demo# grpcurl -plaintext localhost:50052 celestia.prover.v1.Prover/Info
{
"stateTransitionVerifierKey": "0x00dea45f0c890c7bfdbdcbde9b867dc574cb7c4a14d026abc40f8cd4139c3f89"
}
```
> feat: populate Info endpoint with SP1 aggregator verifier key
